import express from 'express'
import multer from 'multer'
import path from 'path'
import { promises as fs } from 'fs'
import { fileURLToPath } from 'url'
import ExcelJS from 'exceljs'
import { File } from '../models/index.js'
import { tokenExtractor } from '../utils/middleware.js'
import { UPLOADS_DIR } from '../utils/config.js'
import { generateProductDataSheetPdf } from '../utils/pdfGenerator.js'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

const router = express.Router()

// Base uploads directory - uses test-uploads in test environment
const uploadsDir = path.join(__dirname, '..', UPLOADS_DIR)
// SAFE: UPLOADS_DIR is controlled via config and not user input
// eslint-disable-next-line security/detect-non-literal-fs-filename
await fs.mkdir(uploadsDir, { recursive: true })

// Helper function to get user-specific directory
const getUserUploadDir = (userId) => {
  return path.join(uploadsDir, String(userId))
}

// Validate filename to prevent path traversal attacks
const isValidFilename = (filename) => {
  if (!filename || filename.trim().length === 0) {
    return false
  }

  const dangerousPatterns = [
    /\.\./,     // Parent directory traversal
    /\//,       // Unix path separator
    /\\/,       // Windows path separator
    /\0/,       // Null byte
    /^\.+$/     // Only dots (., .., ...)
  ]

  return !dangerousPatterns.some(pattern => pattern.test(filename))
}

// Configure multer for file uploads
const storage = multer.diskStorage({
  destination: async (req, file, cb) => {
    try {
      const userDir = getUserUploadDir(req.user.id)
      // SAFE: req.user.id is autogenerated INTEGER from Sequelize User model
      // eslint-disable-next-line security/detect-non-literal-fs-filename
      await fs.mkdir(userDir, { recursive: true })
      cb(null, userDir)
    } catch (error) {
      cb(error)
    }
  },
  filename: (req, file, cb) => {
    const uniqueSuffix = Date.now() + '-' + Math.round(Math.random() * 1000000000)
    cb(null, uniqueSuffix + '-' + file.originalname)
  }
})

const upload = multer({
  storage,
  limits: {
    fileSize: 10 * 1024 * 1024 // 10MB limit
  },
  fileFilter: (req, file, cb) => {
    const allowedMimeTypes = [
      'application/vnd.ms-excel',
      'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      'image/png'
    ]

    if (!isValidFilename(file.originalname)) {
      cb(new Error('Invalid filename: empty name or contains forbidden characters (e.g., .., /, \\)'))
      return
    }

    if (allowedMimeTypes.includes(file.mimetype)) {
      cb(null, true)
    } else {
      cb(new Error('Only Excel files (.xls, .xlsx) and PNG images (.png) are allowed'))
    }
  }
})

router.get('/', tokenExtractor, async (req, res) => {
  const files = await File.findAll({
    where: { userId: req.user.id },
    attributes: ['id', 'originalName', 'fileSize', 'createdAt'],
    order: [['createdAt', 'DESC']]
  })

  res.json(files)
})

router.post('/', tokenExtractor, upload.single('file'), async (req, res, next) => {
  try {
    if (!req.file) {
      return res.status(400).json({ error: 'No file uploaded' })
    }

    const userDir = getUserUploadDir(req.user.id)
    const filePath = path.resolve(req.file.path)

    if (!filePath.startsWith(path.resolve(userDir))) {
      // SAFE: req.file.path is generated by multer in a controlled manner
      // eslint-disable-next-line security/detect-non-literal-fs-filename
      await fs.unlink(filePath).catch((err) => {
        console.error('Failed to delete unauthorized file:', err)
      })
      return res.status(400).json({ error: 'Invalid file path' })
    }

    const file = await File.create({
      filename: req.file.filename,
      originalName: req.file.originalname,
      filePath: req.file.path,
      mimeType: req.file.mimetype,
      fileSize: req.file.size,
      userId: req.user.id
    })

    res.status(201).json({
      id: file.id,
      originalName: file.originalName,
      fileSize: file.fileSize,
      createdAt: file.createdAt
    })
  } catch (error) {
    if (req.file) {
      const filePath = path.resolve(req.file.path)
      const userDir = getUserUploadDir(req.user.id)
      if (filePath.startsWith(path.resolve(userDir))) {
        // SAFE: req.file.path is generated by multer in a controlled manner
        // eslint-disable-next-line security/detect-non-literal-fs-filename
        await fs.unlink(filePath).catch((err) => {
          console.error('Failed to clean up file after error:', err)
        })
      }
    }
    next(error)
  }
})

router.delete('/:id', tokenExtractor, async (req, res, next) => {
  try {
    const fileId = parseInt(req.params.id)

    if (isNaN(fileId)) {
      return res.status(400).json({ error: 'Invalid file ID' })
    }

    const file = await File.findByPk(fileId)

    if (!file) {
      return res.status(404).json({ error: 'File not found' })
    }

    if (file.userId !== req.user.id) {
      return res.status(403).json({ error: 'Access denied' })
    }

    const filePath = path.resolve(file.filePath)
    const userDir = getUserUploadDir(req.user.id)

    if (!filePath.startsWith(path.resolve(userDir))) {
      return res.status(400).json({ error: 'Invalid file path' })
    }

    // SAFE: file.filePath is from database and validated above
    // eslint-disable-next-line security/detect-non-literal-fs-filename
    await fs.unlink(filePath)
    await file.destroy()

    res.status(204).end()
  } catch (error) {
    next(error)
  }
})

router.get('/:id/pdf', tokenExtractor, async (req, res, next) => {
  try {
    const fileId = parseInt(req.params.id)

    if (isNaN(fileId)) {
      return res.status(400).json({ error: 'Invalid file ID' })
    }

    const file = await File.findByPk(fileId)

    if (!file) {
      return res.status(404).json({ error: 'File not found' })
    }

    if (file.userId !== req.user.id) {
      return res.status(403).json({ error: 'Access denied' })
    }

    const filePath = path.resolve(file.filePath)
    const userDir = getUserUploadDir(req.user.id)

    if (!filePath.startsWith(path.resolve(userDir))) {
      return res.status(400).json({ error: 'Invalid file path' })
    }

    let excelData = []
    try {
      const workbook = new ExcelJS.Workbook()
      await workbook.xlsx.readFile(filePath)

      const worksheet = workbook.worksheets[0]

      if (!worksheet) {
        return res.status(400).json({ error: 'Excel file contains no worksheets' })
      }

      worksheet.eachRow((row) => {
        excelData.push(row.values.slice(1))
      })
    } catch {
      return res.status(400).json({ error: 'Failed to parse Excel file. File may be corrupted.' })
    }

    res.setHeader('Content-Type', 'application/pdf')
    res.setHeader('Content-Disposition', 'inline; filename="Product Name.pdf"')

    await generateProductDataSheetPdf(excelData, res)
  } catch (error) {
    next(error)
  }
})

export default router