import path from 'path'
import { fileURLToPath } from 'url'
import { promises as fs } from 'fs'
import ExcelJS from 'exceljs'
import { File } from '../models/index.js'
import { UPLOADS_DIR } from './config.js'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

const uploadsDir = path.join(__dirname, '..', UPLOADS_DIR)

export const initializeUploadsDir = async () => {
  // SAFE: UPLOADS_DIR is controlled via config and not user input
  // eslint-disable-next-line security/detect-non-literal-fs-filename
  await fs.mkdir(uploadsDir, { recursive: true })
}

export const getUserUploadDir = (userId) => {
  return path.join(uploadsDir, String(userId))
}

export const isValidFilename = (filename) => {
  if (!filename || filename.trim().length === 0) {
    return false
  }

  const dangerousPatterns = [
    /\.\./,     // Parent directory traversal
    /\//,       // Unix path separator
    /\\/,       // Windows path separator
    /\0/,       // Null byte
    /^\.+$/     // Only dots (., .., ...)
  ]

  return !dangerousPatterns.some(pattern => pattern.test(filename))
}

export const validateAndParseExcel = async (req, res) => {
  const fileId = parseInt(req.params.id)

  if (isNaN(fileId)) {
    res.status(400).json({ error: 'Invalid file ID' })
    return null
  }

  const file = await File.findByPk(fileId)

  if (!file) {
    res.status(404).json({ error: 'File not found' })
    return null
  }

  if (file.userId !== req.user.id) {
    res.status(403).json({ error: 'Access denied' })
    return null
  }

  const filePath = path.resolve(file.filePath)
  const userDir = getUserUploadDir(req.user.id)

  if (!filePath.startsWith(path.resolve(userDir))) {
    res.status(400).json({ error: 'Invalid file path' })
    return null
  }

  let excelData = []
  try {
    const workbook = new ExcelJS.Workbook()
    await workbook.xlsx.readFile(filePath)

    const worksheet = workbook.worksheets[0]

    if (!worksheet) {
      res.status(400).json({ error: 'Excel file contains no worksheets' })
      return null
    }

    worksheet.eachRow((row) => {
      excelData.push(row.values.slice(1))
    })
  } catch {
    res.status(400).json({ error: 'Failed to parse Excel file. File may be corrupted.' })
    return null
  }

  return excelData
}

export const generateUniqueFilename = (originalName) => {
  const uniqueSuffix = `${Date.now()}-${Math.round(Math.random() * 1000000000)}`
  return `${uniqueSuffix}-${originalName}`
}

const EXAMPLE_FILES = [
  { name: 'Test-logo.png', mimeType: 'image/png' },
  { name: 'Test-product.png', mimeType: 'image/png' },
  { name: 'Test-sheet.xlsx', mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' },
]

const exampleFilesDir = path.join(__dirname, '..', '..', 'example-files')

export const seedExampleFiles = async (userId) => {
  try {
    const userDir = getUserUploadDir(userId)
    // SAFE: userId is an autogenerated INTEGER from the User model
    // eslint-disable-next-line security/detect-non-literal-fs-filename
    await fs.mkdir(userDir, { recursive: true })

    for (const { name, mimeType } of EXAMPLE_FILES) {
      const uniqueFilename = generateUniqueFilename(name)
      const sourcePath = path.join(exampleFilesDir, name)
      const destPath = path.join(userDir, uniqueFilename)

      // SAFE: paths are constructed from controlled constants and userId (integer)
      await fs.copyFile(sourcePath, destPath)
      // eslint-disable-next-line security/detect-non-literal-fs-filename
      const { size } = await fs.stat(destPath)

      await File.create({
        filename: uniqueFilename,
        originalName: name,
        filePath: destPath,
        mimeType,
        fileSize: size,
        userId,
      })
    }
  } catch (error) {
    console.error('Failed to seed example files for user', userId, error)
  }
}
